### ISSUE TITLE
Templates in subdirectories

### ISSUE THREAD

**Issue by mschwartz** [steveukx/hogan-middleware#2]
It's really great that partials can exist in subdirectories.  However, I would love to be able to do things like:

```
res.render('path/to/template', ...}
```

And in my templates:

```
{{> path/to/template }}
```

Then I can organize my templates and partials more conveniently.

These are PAGE templates, not partials:
user-settings/
user-settings/password.mustache
user-settings/avatar.mustache
common/
common/header.mustache
common/footer.mustache

```
res.render('user-settings/password', { ... })
```

And in my user-settings.mustache:

```
{{> common/header }}
...
{{> common/footer }}
```

Additionally, I would like to have templates with the same name:

news/
news/edit.mustache
news/detail.mustache
events/
events/edit.mustache
events/detail.mustache

Since I am including path in my templates to include partials, there is no name collisions.

```
res.render('news/edit', { ... })
// and
res.render('events/edit', { ... }}
```

**Comment by steveukx** [comment]
From version 0.2.1 you are now able to reference partials using their relative path from the main view directory (as set in the express settings):

```
// index.mustache
<section> {{>news/main}} </section>
<section> {{>events/main}} </section>

// news/main.mustache
Can refer to events as {{>events/main}} or other items in news as {{>news/detail}}
```

By default (and for backwards compatibility) the paths are still collapsed, to stop flattening the partials to their base name only, add a [configuration setting](https://github.com/steveukx/hogan-middleware#configuration) for `flatten: false` .

**Comment by mschwartz** [comment]
That's fine, but I want my main templates to be in subdirectories, too.

I tried this and it did not work:

res.render({ 'page/edit', { ... })

edit.mustache is in the page/ subdirectory

I want to use common/header and common/footer which are ../common/header(footer) from the page/edit page template.

**Comment by steveukx** [comment]
I see what you mean - `0.2.2` should cater for specifying a nested path in the `res.render` call.

**Comment by mschwartz** [comment]
I notice that Hogan hasn't had a PR merged or a commit done in quite a while.  I wonder if it's abandoned.

I have a pages section of the site, and a news section, and an events section.

My previous implementation had pages/edit.mustache, pages/detail.mustache, pages/list.mustache, etc.  For news, very similar: news/edit.mustache, news/detail.mustache, news/list.mustache.

To make it work with this plugin, I had to rename my templates and move them into the root of the views folder.  Something like:

NewsEdit.mustache, NewsDetail.mustache, etc.

Within my original templates, I had {{> common/header }} and {{> common/footer }}.  Those were relative to the views directory, not to the actual template's.  Thus:

common/
common/header.mustache
common/footer.mustache
news/
news/view.mustache

In news/view.mustache, {{> common/header }} should work... I don't think it makes sense to force me to use a path like {{> ../common/header }}

FWIW
